package elearningBatch.model;

import java.util.Date;

public class Content {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.ques_num
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    private String quesNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.scope
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    private Long scope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.ques
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    private Long ques;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.ques_name
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    private String quesName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.detail
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.rule
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    private String rule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.sdate
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    private Date sdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.acess_flg
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    private Short acessFlg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.ques_num
     *
     * @return the value of content.ques_num
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public String getQuesNum() {
        return quesNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.ques_num
     *
     * @param quesNum the value for content.ques_num
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public void setQuesNum(String quesNum) {
        this.quesNum = quesNum == null ? null : quesNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.scope
     *
     * @return the value of content.scope
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public Long getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.scope
     *
     * @param scope the value for content.scope
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public void setScope(Long scope) {
        this.scope = scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.ques
     *
     * @return the value of content.ques
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public Long getQues() {
        return ques;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.ques
     *
     * @param ques the value for content.ques
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public void setQues(Long ques) {
        this.ques = ques;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.ques_name
     *
     * @return the value of content.ques_name
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public String getQuesName() {
        return quesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.ques_name
     *
     * @param quesName the value for content.ques_name
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public void setQuesName(String quesName) {
        this.quesName = quesName == null ? null : quesName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.detail
     *
     * @return the value of content.detail
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.detail
     *
     * @param detail the value for content.detail
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.rule
     *
     * @return the value of content.rule
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public String getRule() {
        return rule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.rule
     *
     * @param rule the value for content.rule
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public void setRule(String rule) {
        this.rule = rule == null ? null : rule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.sdate
     *
     * @return the value of content.sdate
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public Date getSdate() {
        return sdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.sdate
     *
     * @param sdate the value for content.sdate
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public void setSdate(Date sdate) {
        this.sdate = sdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.acess_flg
     *
     * @return the value of content.acess_flg
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public Short getAcessFlg() {
        return acessFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.acess_flg
     *
     * @param acessFlg the value for content.acess_flg
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public void setAcessFlg(Short acessFlg) {
        this.acessFlg = acessFlg;
    }

    @Override
    public String toString() {
        return "Content [quesNum=" + quesNum + ", scope=" + scope + ", ques="
                + ques + ", quesName=" + quesName + ", detail=" + detail
                + ", rule=" + rule + ", sdate=" + sdate + ", acessFlg="
                + acessFlg + "]";
    }

    
}