package elearningBatch.model;

import java.util.Date;

public class Lab {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lab.scope
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    private Integer scope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lab.scope_name
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    private String scopeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lab.sdate
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    private Date sdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lab.acess_flg
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    private Short acessFlg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lab.scope
     *
     * @return the value of lab.scope
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public Integer getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lab.scope
     *
     * @param scope the value for lab.scope
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public void setScope(Integer scope) {
        this.scope = scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lab.scope_name
     *
     * @return the value of lab.scope_name
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public String getScopeName() {
        return scopeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lab.scope_name
     *
     * @param scopeName the value for lab.scope_name
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public void setScopeName(String scopeName) {
        this.scopeName = scopeName == null ? null : scopeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lab.sdate
     *
     * @return the value of lab.sdate
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public Date getSdate() {
        return sdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lab.sdate
     *
     * @param sdate the value for lab.sdate
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public void setSdate(Date sdate) {
        this.sdate = sdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lab.acess_flg
     *
     * @return the value of lab.acess_flg
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public Short getAcessFlg() {
        return acessFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lab.acess_flg
     *
     * @param acessFlg the value for lab.acess_flg
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public void setAcessFlg(Short acessFlg) {
        this.acessFlg = acessFlg;
    }

    @Override
    public String toString() {
        return "Lab [scope=" + scope + ", scopeName=" + scopeName + ", sdate="
                + sdate + ", acessFlg=" + acessFlg + "]";
    }

    
}