package elearningBatch.model;

import java.util.Date;

public class TeamInf {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_inf.team_id
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    private String teamId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_inf.team_name
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    private String teamName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_inf.s_date
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    private Date sDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_inf.e_date
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    private Date eDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_inf.team_id
     *
     * @return the value of team_inf.team_id
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public String getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_inf.team_id
     *
     * @param teamId the value for team_inf.team_id
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public void setTeamId(String teamId) {
        this.teamId = teamId == null ? null : teamId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_inf.team_name
     *
     * @return the value of team_inf.team_name
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public String getTeamName() {
        return teamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_inf.team_name
     *
     * @param teamName the value for team_inf.team_name
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public void setTeamName(String teamName) {
        this.teamName = teamName == null ? null : teamName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_inf.s_date
     *
     * @return the value of team_inf.s_date
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public Date getsDate() {
        return sDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_inf.s_date
     *
     * @param sDate the value for team_inf.s_date
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public void setsDate(Date sDate) {
        this.sDate = sDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_inf.e_date
     *
     * @return the value of team_inf.e_date
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public Date geteDate() {
        return eDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_inf.e_date
     *
     * @param eDate the value for team_inf.e_date
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public void seteDate(Date eDate) {
        this.eDate = eDate;
    }

    @Override
    public String toString() {
        return "TeamInf [teamId=" + teamId + ", teamName=" + teamName
                + ", sDate=" + sDate + ", eDate=" + eDate + "]";
    }

    
}