package elearningBatch.model;

import java.util.Date;

public class UserInf {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.user_id
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.team_id
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    private String teamId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.password
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.user_name
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.gender
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    private Short gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.age
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.exp
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    private Integer exp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.s_date
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    private Date sDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.e_date
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    private Date eDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.user_id
     *
     * @return the value of user_inf.user_id
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.user_id
     *
     * @param userId the value for user_inf.user_id
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.team_id
     *
     * @return the value of user_inf.team_id
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public String getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.team_id
     *
     * @param teamId the value for user_inf.team_id
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public void setTeamId(String teamId) {
        this.teamId = teamId == null ? null : teamId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.password
     *
     * @return the value of user_inf.password
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.password
     *
     * @param password the value for user_inf.password
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.user_name
     *
     * @return the value of user_inf.user_name
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.user_name
     *
     * @param userName the value for user_inf.user_name
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.gender
     *
     * @return the value of user_inf.gender
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public Short getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.gender
     *
     * @param gender the value for user_inf.gender
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public void setGender(Short gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.age
     *
     * @return the value of user_inf.age
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.age
     *
     * @param age the value for user_inf.age
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.exp
     *
     * @return the value of user_inf.exp
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public Integer getExp() {
        return exp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.exp
     *
     * @param exp the value for user_inf.exp
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public void setExp(Integer exp) {
        this.exp = exp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.s_date
     *
     * @return the value of user_inf.s_date
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public Date getsDate() {
        return sDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.s_date
     *
     * @param sDate the value for user_inf.s_date
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public void setsDate(Date sDate) {
        this.sDate = sDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.e_date
     *
     * @return the value of user_inf.e_date
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public Date geteDate() {
        return eDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.e_date
     *
     * @param eDate the value for user_inf.e_date
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    public void seteDate(Date eDate) {
        this.eDate = eDate;
    }

    @Override
    public String toString() {
        return "UserInf [userId=" + userId + ", teamId=" + teamId
                + ", userName=" + userName + ", gender=" + gender + ", age="
                + age + ", exp=" + exp + ", sDate=" + sDate + ", eDate=" + eDate
                + "]";
    }

}