package elearningBatch.mapper;

import elearningBatch.model.Content;

public interface ContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    int deleteByPrimaryKey(String quesNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    int insert(Content row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    int insertSelective(Content row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    Content selectByPrimaryKey(String quesNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    int updateByPrimaryKeySelective(Content row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table content
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    int updateByPrimaryKey(Content row);
}