package elearningBatch.mapper;

import elearningBatch.model.UnitTest;

public interface UnitTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_test
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    int deleteByPrimaryKey(String sourceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_test
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    int insert(UnitTest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_test
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    int insertSelective(UnitTest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_test
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    UnitTest selectByPrimaryKey(String sourceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_test
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    int updateByPrimaryKeySelective(UnitTest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_test
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    int updateByPrimaryKeyWithBLOBs(UnitTest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_test
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    int updateByPrimaryKey(UnitTest row);
}