package elearningBatch.mapper;

import elearningBatch.model.UserInf;

public interface UserInfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_inf
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_inf
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    int insert(UserInf row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_inf
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    int insertSelective(UserInf row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_inf
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    UserInf selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_inf
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    int updateByPrimaryKeySelective(UserInf row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_inf
     *
     * @mbg.generated Sun Jan 26 13:43:25 JST 2025
     */
    int updateByPrimaryKey(UserInf row);
}